### ISSUE TITLE
[BUG] Issue in HMM search and parse of pdb_seqres.txt 

### ISSUE THREAD

**Issue by yeopyeob** [seoklab/alphafold#4] opened 2022-12-27 06:17 UTC
I run the AlphaFold-multimer for the homomer of ACTA1

Run is failed with next message,

```
Traceback (most recent call last):
   File "/applic/AlphaFold/current/run_alphafold.py", line 714, in <module>
     app.run(main, flags_parser=fasta_parser)
   File "/opt/conda/envs/alphafold2/lib/python3.8/site-packages/absl/app.py", line 312, in run
     _run_main(main, args)
   File "/opt/conda/envs/alphafold2/lib/python3.8/site-packages/absl/app.py", line 258, in _run_main
     sys.exit(main(argv))
   File "/applic/AlphaFold/current/run_alphafold.py", line 697, in main
     predict_structure(fasta_path=fasta_path,
   File "/applic/AlphaFold/current/run_alphafold.py", line 536, in predict_structure
     feature_dict = _preprocess(fasta_path, output_dir, data_pipeline, overwrite)
   File "/applic/AlphaFold/current/run_alphafold.py", line 417, in _preprocess
     feature_dict = data_pipeline.process(
   File "/applic/AlphaFold/2.2.9/alphafold/data/pipeline_multimer.py", line 262, in process
     chain_features = self._process_single_chain(
   File "/applic/AlphaFold/2.2.9/alphafold/data/pipeline_multimer.py", line 210, in _process_single_chain
     chain_features = self._monomer_data_pipeline.process(
   File "/applic/AlphaFold/2.2.9/alphafold/data/pipeline.py", line 193, in process
     pdb_templates_result = self.template_searcher.query(msa_for_templates)
   File "/applic/AlphaFold/2.2.9/alphafold/data/tools/hmmsearch.py", line 82, in query
     return self.query_with_hmm(hmm)
   File "/applic/AlphaFold/2.2.9/alphafold/data/tools/hmmsearch.py", line 115, in query_with_hmm
     raise RuntimeError(
 RuntimeError: hmmsearch failed:
```

and

```
 Parse failed (sequence file /applic/AlphaFold/current/data/pdb_seqres/pdb_seqres.txt):
 Line 1366716: illegal character 0
```

AF-monomer for only one unit run well now.

**Comment by yeopyeob** [comment] 2022-12-27 07:46
![image](https://user-images.githubusercontent.com/92566455/209630776-e80914c7-964e-431d-be66-c1dd6addeeb8.png)

I checked the file where error came out, it has the wrong information. I wonder why there are RNA and DNA information.

**Comment by jnooree** [comment] 2022-12-28 02:08
Related issue: https://github.com/deepmind/alphafold/issues/569

**Comment by yeopyeob** [comment] 2023-01-02 14:21
The same problem has occurred again.

**Comment by yeopyeob** [comment] 2023-01-02 14:22
![image](https://user-images.githubusercontent.com/92566455/210243903-49025f13-139f-435d-89b8-302a48239da3.png)

**Comment by jnooree** [comment] 2023-01-02 15:56
Which node was it? I'll close this issue for now since the problem is unrelated to this repo.

**Closed as completed** 2023-01-02 15:56 UTC
Labels: bug
